name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:
  repository_dispatch:  

jobs:
  job1:
   runs-on: ubuntu-latest
   outputs:
      output1: ${{ steps.trigger-step2.outputs.output1 }}
   steps: 
   
     - name: Trigger the Workflow in auto gatling execution Repository
       id: trigger-step
       uses: the-actions-org/workflow-dispatch@v4 
       with:
           workflow: Another Workflow
           repo: sudhakarsuruliraj10/repo2
           token: ${{ secrets.ACTIONS_KEY  }}
           workflow-logs: json-output
           wait-for-completion-timeout: 30s
           wait-for-completion-interval: 10s
           display-workflow-run-url-interval: 10s
           display-workflow-run-url-timeout: 10s  
           wait-for-completion: true
           inputs: >-
            {
            "run-name": "12345"
            }
     - name: Get Job Logs
       id: get_job_logs
       run: |
          curl -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" \
          -X POST \
          "https://api.github.com/sudhakarsuruliraj10/repo2/actions/runs/${{ steps.trigger-step.outputs.workflow-id }}/jobs" \ 
          -d '{"data": "Job data"}' 

     - name: Display Step Names
       run: |       
        echo "${{ steps.get_job_logs.outputs.step_names }}"   

     - name: Display extracted names
       run: |
        cat names.txt
        
     - name: Fetch remote job output
       run: |
           curl -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" \
                https://api.github.com/sudhakarsuruliraj10/repo2/actions/runs/${{ steps.trigger-step.outputs.workflow-id }}/jobs \
                 | jq '.jobs[] | select(.name == "example_job") | .steps[] | .outputs'
