name: Get Workflow Run ID

on:
  workflow_dispatch:

jobs:
  get_run_id:
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Run ID
        id: get_run_id
        run: |
          echo "::set-output name=run_id::${{ github.run_id }}" 

      - name: Log Workflow Run ID
        run: |
          echo "Workflow Run ID: ${{ steps.get_run_id.outputs.run_id }}" 
          echo "TOken: ${{ secrets.ACTIONS_KEY  }}" 
