name: List Workflow Runs (Shell)

on:
  workflow_dispatch:

jobs:
  list_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List Workflow Runs
        run: |
          # Install jq for JSON processing
          sudo apt-get update
          sudo apt-get install jq

          # Get latest workflow run ID
          latest_run_id=$(curl "https://api.github.com/repos/sudhakarsuruliraj10/repo2/actions/workflows/set_output_job/dispatches" -s \
                          -H "Authorization: Token ${{ secrets.GITHUB_TOKEN }}" \
                          -d '{
                          "ref":"main",
                          "inputs":{
                           "id":"12345678"
                            }}')

          # Print the list of run IDs
          echo "Workflow Run IDs:"
          echo "$workflow_runs" 
