name: Trigger and Get Latest Run ID

on:
  workflow_dispatch:

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        id: trigger_workflow
        run: |
          curl "https://api.github.com/repos/sudhakarsuruliraj10/repo2/actions/workflows/set_output_job/dispatches" -s \
                          -H "Authorization: Token ${{ secrets.GITHUB_TOKEN }}" \
                          -d '{
                          "ref":"main",
                          "inputs":{
                           "id":"12345678"
                            }}'
              > trigger_response.json

      - name: Get Triggered Run ID
        id: get_triggered_run_id
        run: |
          triggered_run_id=$(jq -r '.id' trigger_response.json)
          echo "::set-output name=triggered_run_id::$triggered_run_id"

      - name: Log Triggered Run ID
        run: |
          echo "Triggered Run ID: ${{ steps.get_triggered_run_id.outputs.triggered_run_id }}"
