name: Trigger and Get Latest Run ID

on:
  workflow_dispatch:

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        id: trigger_workflow
        run: |
          latest_run_id=$(curl -s -X POST \
               -H "Authorization: Token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               -d '{"ref": "main"}' \ 
               "https://api.github.com/repos/sudhakarsuruliraj10/repo2/actions/workflows/set_ouput_job/dispatches" \
               )

      - name: Get Triggered Run ID
        id: get_triggered_run_id
        run: |
          triggered_run_id=$(jq -r '.id' trigger_response.json)
          echo "::set-output name=triggered_run_id::$triggered_run_id"

      - name: Log Triggered Run ID
        run: |
          echo "Triggered Run ID: ${{ steps.get_triggered_run_id.outputs.triggered_run_id }}"
