name: Get Latest Workflow Run ID (Shell)

on:
  workflow_dispatch:

jobs:
  get_latest_run_id:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Workflow Run ID
        id: get_latest_run_id
        run: |
          latest_run_id=$(curl -s -H "Authorization: token ${{ secrets.ACTIONS_KEY }}" \
                             -H "Accept: application/vnd.github+json" \
                             "https://api.github.com/repos/annamalaiponnusamy/repo_02/actions/runs/13010001391/jobs" \
                             | jq -r '.workflow_runs[0].id')
           echo "::set-output name=latest_run_id::$latest_run_id"
      - name: Log Latest Workflow Run ID
        run: |
          jobs_json=$(curl -S -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" "https://api.github.com/repos/inContact/qa-aspf-lab-dynamic-autoscale/actions/runs/13026385289/jobs")
            echo "$jobs_json" | jq . # Pretty-print the JSON output
