name: Get Latest Workflow Run

on:
  workflow_dispatch:

jobs:
  get_latest_run:
    runs-on: ubuntu-latest
    steps:
      - run: npm i @octokit/rest
      - name: Get Latest Workflow Run
        id: get_latest_run
        uses: actions/github-script@v6
        with:
          script: |
            const octokit = require('@octokit/rest')()
            octokit.auth('token ${{ secrets.GITHUB_TOKEN }}')

            const { data: latestRuns } = await octokit.actions.listWorkflowRuns({
              owner: sudhakarsuruliraj10,
              repo: repo2,
              workflow_file_name: 'Target.yaml',
              per_page: 1, 
            })

            if (latestRuns.length > 0) {
              core.setOutput('latest_run_id', latestRuns[0].id)
              core.setOutput('latest_run_status', latestRuns[0].status) 
            } else {
              core.setOutput('latest_run_id', 'No runs found')
              core.setOutput('latest_run_status', 'No runs found')
            }

      - name: Log Latest Workflow Run Information
        run: |
          echo "Latest Workflow Run ID: ${{ steps.get_latest_run.outputs.latest_run_id }}"
          echo "Latest Workflow Run Status: ${{ steps.get_latest_run.outputs.latest_run_status }}"
