name: List Workflow Runs (Shell)

on:
  workflow_dispatch:

jobs:
  list_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List Workflow Runs
        run: |
          # Install jq for JSON processing
          sudo apt-get update
          sudo apt-get install jq

          # Get list of workflow runs (replace with your actual workflow ID)
          workflow_runs=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                             -H "Accept: application/vnd.github+json" \
                             "https://github.com/sudhakarsuruliraj10/repo2/actions/runs" | \
                             jq -r '.workflow_runs[].id')

          # Print the list of run IDs
          echo "Workflow Run IDs:"
          echo "$workflow_runs" 
