name: List Workflow Runs (Shell)

on:
  workflow_dispatch:

jobs:
  list_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List Workflow Runs
        run: |
          # Install jq for JSON processing
          sudo apt-get update
          sudo apt-get install jq

          # Get latest workflow run ID
          latest_run_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                             -H "Accept: application/vnd.github+json" \
                             "https://api.github.com/repos/repo2/actions/workflows/${{ github.workflow_id }}/runs \
                             | jq -r '.workflow_runs[0].id')

          # Print the list of run IDs
          echo "Workflow Run IDs:"
          echo "$workflow_runs" 
